### PR TITLE
Bugfixes galore

### PR DESCRIPTION
**Pull request by onpon4**
I forgot to consider the case of the cap being nil in #938. Fixed here. Also tweaked the pirate reputation titles a bit.

### CODE REVIEW

**Comment by onpon4** [comment]
One more enhancement: I've made pirate transport missions always show up on pirate worlds that offer missions (if destinations are available).

**Comment by onpon4** [comment]
I've pushed another fix: pirate shipping missions never choose a pirate stronghold as their destination.

**Comment by onpon4** [comment]
Noticed some massive problems with the "foodbiz" campaign, so I almost completely rewrote that. Also fixed a typo in the pirate cargo missions.

**Comment by bobbens** [comment]
Looks good, thanks.

**Pull request merged**
