### PR TITLE
Strangely, _putenv_s can be declared but not getenv_s. The simplest fix is just using getenv here.

### PR DESCRIPTION
**Pull request by UncombedCoconut**
(env_detect() directly above needs it anyway.)

### CODE REVIEW

**Comment by bobbens** [comment]
Wouldn't it be better to put a check for `getenv_s`?

**Comment by UncombedCoconut** [comment]
Depending on your priorities, it could be, and I can put that change together. (Up to and including the implementation of an "ngetenv", I guess.)
Though I'll note that this mode (!overwrite) is only used in case HAS_UNIX is set, to default SDL_VIDEO_X11_WMCLASS. So the main benefit to changing anything is avoiding an implicit getenv_s declaration warning.

**Comment by bobbens** [comment]
> Depending on your priorities, it could be, and I can put that change together. (Up to and including the implementation of an "ngetenv", I guess.)
> Though I'll note that this mode (!overwrite) is only used in case HAS_UNIX is set, to default SDL_VIDEO_X11_WMCLASS. So the main benefit to changing anything is avoiding an implicit getenv_s declaration warning.

That's a good point, we should probably not overwrite `LANGUAGE` too if the user set it.

**Comment by bobbens** [comment]
I've added a check for `getenv_s` instead, just to be safe! 50343ca270c1ce0dff577a7c72f5df82ded9ee7e

**Comment by UncombedCoconut** [comment]
> > Depending on your priorities, it could be, and I can put that change together. (Up to and including the implementation of an "ngetenv", I guess.)
> > Though I'll note that this mode (!overwrite) is only used in case HAS_UNIX is set, to default SDL_VIDEO_X11_WMCLASS. So the main benefit to changing anything is avoiding an implicit getenv_s declaration warning.
> 
> That's a good point, we should probably not overwrite `LANGUAGE` too if the user set it.

Hmm, it's probably OK to do that, as long as the user has picked the language in the options dialog and restarted Naev.

**Pull request closed without merging**
