### PR TITLE
Minor asset fix

### PR DESCRIPTION
**Pull request by kernhe**
Sirius military facility now produces Sirius ships and no longer Soromid ships.

### CODE REVIEW

**Comment by bobbens** [comment]
Looks good, thanks!

**Comment by bobbens** [comment]
For future note, it's best to not do changes directly in your master, but create another branch for the pull request. Don't worry too much about it though, I rebased to master before committing. Thanks again.

**Comment by kernhe** [comment]
Can you tell me why there is a different name for me in the pull request?

**Comment by bobbens** [comment]
You mean in the commit message? I assume this is how you have configured your ~/.gitconfig

**Pull request closed without merging**
