### PR TITLE
Recreated point-defense turrets

### PR DESCRIPTION
**Pull request by PhoenixRiver**
In response to #2119 - I made the following to help out trader players - and maybe the AI once I work out where to fix that... oh, and I also fixed the description of the MK1 laser turrets ; )

I was guessing that the "resist" entry in the launchers was how destructible the projectile was and have thus added it to all the launchers which describe launching a physical object (i.e. I left the plasma launchers alone) making a number more of the missiles, rockets and grenades destructable, I find it odd they weren't already.
I also created two point defense turrets. I'll explain the reasoning behind their stats:
They have high CPU - tracking objects that small and fast is harder than targetting ships (and traders have few weapons and can spare the CPU cycles so these turrets are less use to combat ships which have armour and shields too).
They are cheap but make up for that in combat effectiveness... 1200 trackmax and 350 range. The amount of heat they produce is disproportionate to their damage energy and speed due to the computation and finely tuned wavelengths specifically aimed at taking out individual types of missiles, rockets and grenades and thus are heat inefficient but then again a trader isn't produce heat from their main guns (like as not) so it's not an issue for a trader (unlike a combat ship).
Their shots penetrate well and damage is higher than standard lasers due to the precision of their shots and specificity of their wavelengths matching their target.

So, these weapons are heat and CPU inefficient but highly capable close in to the ship, firing faster and hitting harder at targets that get close enough to be a danger... indicentally they might well be useful against fighters that do suicide runs or hover over the ship but such sitting ducks were always easy chaff! ; )

Edit - I forgot to add that I am perfectly happy for these to receive changes but I thought I'd start the ball rolling in what I think is the right direction... I'm happy for their range to reduce further as long as they have time to track missiles... I also forgot to mention the damage means they'll destroy small ordinence in one shot, medium ordinence in two to five shots and large ordinence probably never since they won't have time before it hits due to their range (but it would be nine shots I think).

### CODE REVIEW

**Comment by not-pyroman** [comment]
actually, the resist stat controls how resistant the projectile is to jamming, for projectiles that do lock on that is

**Comment by PhoenixRiver** [comment]
> actually, the resist stat controls how resistant the projectile is to jamming, for projectiles that do lock on that is take for example the Za'lek Hunter launcher, in game the stats say it has a 35% jamming resistance, and if you look at its XML file you will see that the resist stat there is also 35

Gah! Do you know which stats is used for a missile's armour? I'll have another dig but I'm new to the weapons game :(

**Comment by PhoenixRiver** [comment]
Oh, just discovered that we don't have weapon on weapon collision at the moment... so PD weapons don't work... gah... I'll change back the resist stats and leave this here for now in case someone wants example PD weapons for testing solutions to this problem e.g. #2053

**Comment by PhoenixRiver** [comment]
I guess traders will just have to wait for protection... *sigh*

**Comment by bobbens** [comment]
Yes, point defenses are planned, but I want to finish and merge the `fleets` branch first before working on that. Although I may take a hiatus to work on missions a bit. I'll keep this open until point defense gets implemented and then try to work it into that.

**Comment by PhoenixRiver** [comment]
Thank you :)

**Comment by bobbens** [comment]
As of latest main, point defense weapons are now possible. I'll be adding some in similar vein, but quite different than this PR, so I'm closing. If you want work on other point defense weapons I can share my notes and we can work from there. Thanks!

**Comment by bobbens** [comment]
For reference, the new point defense outfits can be found at https://github.com/naev/naev/tree/main/dat/outfits/pointdefense

**Pull request closed without merging**
