### PR TITLE
Resolved unidiff issue

### PR DESCRIPTION
**Pull request by agb32**
The unidiff system was wiping player economy knowledge information.  This pull resolves it.

### CODE REVIEW

**Comment by nenau-again** [comment]
I did not think about that! The economy info was erased at https://github.com/naev/naev/blob/master/src/economy.c#L869, right?
If yes, why not splitting `economy_initialiseCommodityPrices` in two. One part that initialize the prices, and the other one to erase the economy info, and call only the first one after the unidiff.

Because I believe that it's saner to re-generate all prices after each unidiff. As a matter of fact, prices on other assets can be impacted by the appearence or the disappearance of a planet, and switching to a longer-range price computation system would require to recompute everything each time any asset changes.
What is more, unidiffs can do much more than creating planets. One can for example change faction of planets, or suppress assets... 

What do you think ?

**Comment by agb32** [comment]
No, the economy info was erased at   [https://github.com/naev/naev/blob/master/src/economy.c#628](url) and for the next 4 lines.
So, yes, I've now split it - the unidiff reinitialises the whole economy, but the player info is saved.  This is only reinitialised upon load game or new game.

**Comment by nenau-again** [comment]
> reinitialised upon load game

Does it mean that each time I load a game, the player's price knowledge disappear ?
Shouldn't such info be stored in the save file ?

**Comment by agb32** [comment]
No - this info is stored in your save file, so loads correctly.
But, it reinitialises it because if you load a different save file, it all needs to be reset, except for the stuff in the save file...
So - it will work as you expect.  And if you create a new game, if starts with no knowledge...

**Pull request merged**
