### PR TITLE
Add new core system icons and cargo hull icons.

### PR DESCRIPTION
**Pull request by V-ktor**
New icons for core systems (2 times more) and cargo hulls.

### CODE REVIEW

**Comment by BTAxis** [comment]
You should also add these to ARTWORK_LICENSE, and if you have higher-res sources, we'll want those for the artwork repo too.

**Comment by bobbens** [comment]
They look great! As BTAxis says, would need your info in [dat/gfx/ARTWORK_LICENSE](https://github.com/naev/naev/blob/master/dat/gfx/ARTWORK_LICENSE) and if possible high quality sources for [naev-artwork repository](https://github.com/naev/naev-artwork/) (separate pull request please)!

**Comment by V-ktor** [comment]
Right, I've forgotten to update the license file.
The specialized core system icons are still missing. I will probably make them this week.

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
