### PR TITLE
Japanese translation of the intro, tutorial mission, and more.

### PR DESCRIPTION
**Pull request by oo13**
Japanese translation of the intro, tutorial mission, and some panels. 

I'm not sure I could add a new language to Naev project on Weblate.

### CODE REVIEW

**Comment by UncombedCoconut** [comment]
Thanks!
Weblate will only allow admins (currently @bobbens or myself) to start translations there. I looked into making this more permissive for volunteers, but I never found a way.
I'm actually not sure what will happen if I merge this and then push the button on Weblate, but that's what I'll try.

**Comment by bobbens** [comment]
I tried it and am getting warnings about missing glyphs. In particular it seems like `fonts/SpaceBar.ttf` and `fonts/IBMPlexSansJP-Medium.otf` are missing. Could you do a [PR on naev-artwork-production](https://github.com/naev/naev-artwork-production/pulls) adding the fonts and related licensing information? The rest seems to be fine and picked up by Naev already. We'll merge the naev-artwork-production PR first, update the `artwork` submodule and then merge this PR for a smooth transition.

**Comment by oo13** [comment]
Thanks. I posted a PR to naev-artwork-production.

**Comment by bobbens** [comment]
Thanks, it looks good here now.

**Pull request merged**
