### PR TITLE
Commodities tab images

### PR DESCRIPTION
**Pull request by Mutos**
Adds images to Commodities, stored in a /dat/gfx/commodity folder, referenced in commodity.xml by a <gfx_store> tag, and displayed in the Commodities Tab on landing.

Current images are taken from Vega Strike, it would be nice to make specific NAEV images.

This PR replaces closed PR#568 "Trade imagearray ". It is based on current project state, including PR#570 "Fixed 2 bugs in Image Widget : see comment for details" whose fixes it uses.

### CODE REVIEW

**Comment by bobbens** [comment]
Could you please add the newly added files to dat/gfx/ARTWORK_LICENSE?

**Comment by Mutos** [comment]
I look at that asap, this week-end it should be OK

**Comment by Mutos** [comment]
OK, that's it, added the Vega Strike license lines. Also realised that the _default.png container image was mine and added a license line for it also.

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
