### PR TITLE
Corrected a funny bug in the Sirius preach event

### PR DESCRIPTION
**Pull request by nenau**
This one was causing the event to crash in a very annoying way. _ was an integer !

### CODE REVIEW

**Comment by BTAxis** [comment]
That is valid Lua though. Why would it cause a crash?

**Comment by BTAxis** [comment]
Ah, looks like _ is not a special variable but just a convention. Hokay.

**Comment by ids1024** [comment]
Grepping for `for _` shows a lot of code doing this (and probably there are other uses of `_` that aren't caught by that search). Although most of those cases don't then call `_()`.

This is sort of awkward. Using `_` for gettext in some places and in assignment where the value isn't needed is likely to cause issues. So one of those uses should probably be avoided...

**Comment by bobbens** [comment]
Mmmm. Using _,k in enumerate(...) was (is?) encouraged in Lua, but using _(...) for gettext is standard practice which is why this has happened. Things like this really make me appreciate static typed languages ;)

**Comment by PhoenixRiver** [comment]
Yeah, that does suck a bit and static typing definitely does have its
benefits! :D

**Pull request merged**
