### PR TITLE
Rename dat/licenses directory

### PR DESCRIPTION
**Pull request by a-random-lemurian**
```
I thought the code for the in-game licenses was in the licenses folder,
and it wasn't. Hopefully if we rename it to copyright, that confusion
will be solved.

Copyright licenses haven't been deleted, I assume git or github suck
at showing diffs. You might want to review my fork to check.
```

### CODE REVIEW

**Comment by a-random-lemurian** [comment]
Well, I suck at git. We make mistakes sometimes.

**Comment by bobbens** [comment]
I do think it's more confusing if we have a `LICENSE` and other `ARTWORK_LICENSE.yaml` and such files all over, and the folder gets renamed to copyright. An easier more consistent way of distinguishing them would be to just make the directory name uppercase `LICENSE/`, which would be consistent with a) us calling the files LICENSE all over, and b) using all uppercase to denote license files.

**Comment by a-random-lemurian** [comment]
I've force pushed with lease.

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
