### PR TITLE
Starmap

### PR DESCRIPTION
**Pull request by Mutos**
Added back utils/starmap that had been deleted long ago, and enhanced it  with easier to read color settings.

Two points of notice :

- We probably should first investigate about why it had been deleted and whether it allows us to reintegrate it. I made a simple search in Issues and PR and didn't find any clue.

- The current starmap has a few SoC-specific lines in it, to display systems containing asteroids. It uses my old way to make asteroids fields appear in the map by using assets named "Asteroids Cluster xxxxxx". This was before the new asteroids anchors system. It does nothing adverse when reading NAEV data. I'm currently converting my old asteroids-assets into regular asteroids anchors and I'll remove these SoC-specific lines afterwards and present a follow-up PR.

### CODE REVIEW

**Comment by nenau-again** [comment]
Yay, PR#1000 !
For ignorant people like me, could you explain what this script does ?

**Comment by Mutos** [comment]
Hi nenau,

Didn't even notice this was PR#1000 ^-^ thanks for signalling !

It outputs an SVG map of the current universe, see the following examples, converted to PNG to be uploaded on Github :

NAEV :
starmap svg

Stars of Call :
starmap svg

**Comment by nenau-again** [comment]
Mm. Could be useful indeed to have a way to export universe in a clean svg format. Btw, it looks buggy for exit-only jumps (like in Zied).

**Comment by bobbens** [comment]
Looks a bit buggy (some edges are weird like that long one from sioux), but I guess it's a bit better than nothing. If possible some more usability would be nice (--help and allowing running from root directory, readme, etc). However, I think it is better to have than not so merged. Thanks!

**Comment by Mutos** [comment]
Hello bobbens,

Thanks for the appreciation ! I just took it from its previous instalment and enhanced it for better readability, didn't debug it in depth.

**Pull request merged**
