### PR TITLE
Proofread of assets starting with "e" and added Z class planet space image

### PR DESCRIPTION
**Pull request by PhoenixRiver**
I've (after a rather long break) continued with proofreading the assets directory.
This is a pull request for assets starting with "e":
 - primary changes are to asset class
 - then exterior image (in case we ever decide that players can land on planets without spaceports and want to show an image; the exterior images are now at least consistant with the planet class)
 - then typos in planet and bar descriptions
 - finally also added a Z class space planet image which matches the exterior image and description for Eiroik (which reads like it is a mission planet and therefore one that would often would be visited by the player and so ought probably be consistant :)

### CODE REVIEW

**Comment by PhoenixRiver** [comment]
For reference:
There are 115 class 0 stations (civilian).
There are 36 class 1 stations (military).
There are 2 class 2 stations (interfactional).
There are 17 class 3 stations (robotic).
There are 427 class A planets (79% don't match their space GFX).
There are 16 class C planets (19% don't match their space GFX).
There are 35 class D planets (20% don't match their space GFX).
There are 39 class G planets (0% don't match their space GFX).
There are 27 class H planets (12% don't match their space GFX).
There are 34 class I planets (18% don't match their space GFX).
There are 52 class J planets (14% don't match their space GFX).
There are 38 class K planets (14% don't match their space GFX).
There are 15 class L planets (20% don't match their space GFX).
There are 100 class M planets (6% don't match their space GFX).
There are 2 class N planets (100% don't match their space GFX).
There are 51 class O planets (32% don't match their space GFX).
There are 38 class P planets (6% don't match their space GFX).
There are 6 class S planets (0% don't match their space GFX).
There are 20 class X planets (20% don't match their space GFX).
There are 13 class Y planets (31% don't match their space GFX).
There is 1 class Z planet (0% don't match their space GFX).

(after application of this pull request - the numbers come from my upgrades to https://github.com/perey/puntools/ (see my pull request there for details) - hope it helps :)

**Comment by PhoenixRiver** [comment]
Forgot to add - Class A seems ot be the default people have picked when creating planets, hence there being so many, there are no Class N GFX hence the problem with all of them for the foreseeable future.

**Comment by PhoenixRiver** [comment]
Now fixed so it should be able to pull before or after typos_F :)

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
