### PR TITLE
guided ammo behave like bolt weapons and guided ammo always use absolute velocity

### PR DESCRIPTION
**Pull request by nenau-again**
This proposal would solve https://github.com/naev/naev/issues/922

* All unguided rockets (mace and banshee) have 0 thrust and behave like bolt ammo
* All guided rockets have non-zero thrust. The result is that their final speed is always equal to their max_speed, and they sometimes have nice trajectories when launched.
* The way trails colours are chosen has been changed to be coherent with these changes.
* Mace rockets are thus much more effective. As a result, I divided by 2 their reload rate, and their quantity in launcher. This results in this weapon being very effective, but if the shots miss, the attack is a failure.

I know it's not really in par with what was discussed on discord, but it's the easiest solution, implementation-wise, and also probably player-wise. Otherwise we would have to teach the AI to play with this absolute--relative velocity question.
Later on, we can implement unguided ammo sometimes running amok with a low probability, and turning all over the place, mainly for the cool factor.

### CODE REVIEW

**Comment by onpon4** [comment]
I should note that it would be perfectly possible and desirable to make it so that unguided rockets with thrust are aimed for correctly. The current aiming code assumes that all projectiles fired have a linear speed. Add some slightly more advanced math calculating the distance traveled during acceleration to max speed and the time it takes to get to max speed, and thrusting mace rockets would work a whole lot better.

🕵️

**Comment by nenau-again** [comment]
You're totally right. However there are two subtleties:
* There is this absolute/relative velocity problem that makes that the trajectory of thrusting rockets is curvilinear
* The travel time in the case of constant velocity (currently implemented) requires to solve a polynomial equation of order 2. In the present case, with a constant thrust, I suppose it might require to solve an equation of order 3, which solution is analytical IIRC. But if the gods of maths are against us, this relative/absolute issue could require to solve an equation which solution is not analytical, thus requiring to use dichotomy or such, and leading to much more complexity of the code and a possible non-negligible CPU cost.

The present proposal is simply an attempt to get rid of the need of such a feature by removing thrusting unguided rockets. But if the majority of people think, contrary to me, that those rockets should continue existing, I might end up implementing this aiming feature in a short future.

**Comment by onpon4** [comment]
Well currently thrusting rockets don't inherit ships' velocity IIRC, so I'm a little confused. Wouldn't simple kinematic formulas suffice, followed by the same linear logic that is currently used all throughout?

Specifically, the time it takes to accelerate to max speed can be calculated with `v[f] = v[i] + a*t`. `v[i]` is 0, so `t = v[f] / a` (where `v[f]` is the rocket's max speed). Displacement can then be calculated with `d = (v[i]+v[f])/2 * t` (again, `v[i]` is 0, and `v[f]` is the rocket's max speed). This gives us the distance and time traveled while the rocket accelerates to max speed. Then for any additional distance involved, linear logic can determine that.

The only major complication I can think of is if thrusting rockets were made to start with the same velocity as the launching pilot. To be fair, making rockets with thrust have inertia would certainly be a good idea.

🕵️

**Comment by bobbens** [comment]
I pushed my thoughts to `rockets` branch. Notable changes:
1. Split `speed` attribute into `speed_max` and `speed`. `speed_max` refers to maximum speed of the ammo (relative with thrust, absolute otherwise), and `speed` refers to initial speed.
2. All seekers have no initial `speed` (start at parent speed) and have `speed_max` set to the previous `speed` value
3. Banshee and mace rockets have `speed` and `thrust`. They will act similar to bolt weapons, but they do accelerate, and the `speed_max` is relative in this case.
4. Changed `outfit_speed` to handle the new code.
5. Display speed and thrust in outfit description.

I tried it and it feels sort of a blend between the old system and the PR here. AI is much more accurate with the new rockets and they still have a behaviour somewhat different from bolts. It should be possible to tweak the speed and thrush values more to change the behaviour. Except for 56d9803d7fbfe0ab7d1080a9ce3faccafafdc977 the branch should behave exactly like the PR.

**Pull request merged**
