### PR TITLE
added a landing port image for snowy planets

### PR DESCRIPTION
**Pull request by Bisc88**
an image of a landing port built over a small canyon with a frozen river.
snowy_cliffs

### CODE REVIEW

**Comment by bobbens** [comment]
Hello, looks nice! To accept a graphical contribution I'm going to have to ask you to also add the info into "dat/gfx/ARTWORK_LICENSE", which basically just consists of adding how you want to be attributed and the license of the graphic itself (which should be DFSG), then I will be glad to merge it. Thakns!

**Comment by ids1024** [comment]
@Bisc88 Do you have some kind of 3d source file that this is rendered from? It is not really necessary, but it is good to have the 3d source files for all the artwork available.

**Comment by Bisc88** [comment]
@ids1024 yes, I have ([link to the file](http://www.mediafire.com/download/kabrwgl924kp24o/snow_scene.blend)), but the sky is not present because it was added after the render.

**Comment by Bisc88** [comment]
@bobbens You're welcome, information added, now, it is ready to merge :smile:

**Comment by bobbens** [comment]
Looks good, thanks. Now to see which planets to use it for ;)

**Pull request merged**
