### PR TITLE
New core system icons

### PR DESCRIPTION
**Pull request by V-ktor**
Add new icons for the specialized core systems.

### CODE REVIEW

**Comment by nenau-again** [comment]
Hey, wait... Does it mean each single core outfit has its own gfx now ?
If yes, that's awesome !

**Comment by V-ktor** [comment]
I think each core outfit has a unique icon now, except engines.
There is also an icon for each biocore outfit. There should be another one for the last stage, right?

**Comment by onpon4** [comment]
Yeah, I would say that stage X bioship parts should have separate images from the earlier stage bioship parts. But this is great! 😄

**Comment by bobbens** [comment]
Looks great! Thanks.

**Pull request merged**
