### PR TITLE
Fix ldoc generation to make bobbens happy

### PR DESCRIPTION
**Pull request by ProjectSynchro**
Title. 
Turns out you need to configure in order to make :P

Also of note, ldoc should be included in the PATH.
In the case of the runner VM; ldoc is installed locally, therefore the local install path is added to the PATH.

### CODE REVIEW

**Comment by ProjectSynchro** [comment]
One issue with the lua generation.
Just need to fix quickly one commit

**Comment by onpon4** [comment]
L:Hahaha, yes, I was noticing the doc build failure.

**Comment by ProjectSynchro** [comment]
Should be good now :)

**Comment by onpon4** [comment]
Looks like it. Thanks!

🕷️

**Comment by ids1024** [comment]
Would @bobbens be too offended if I suggested it would be better to just call `ldoc.sh` without make to avoid the dependencies? :laughing: 

Otherwise, it would be nice if there's a good way to not have to duplicate the list of dependencies in both this section and the Linux build.

Apparently Ubuntu [packages `ldoc`](https://packages.ubuntu.com/search?searchon=names&keywords=lua-ldoc), so I guess we can at least simplify installation of that. (Perhaps I set up the Travis code before they packaged it? Or at least before Travis defaulted to a version that did...).

**Pull request merged**
