### PR TITLE
H key cycles missions in map window

### PR DESCRIPTION
**Pull request by jjustra**
Player can cycle+autonav its missions from map window.

### CODE REVIEW

**Comment by bobbens** [comment]
Cool idea! However, I don't think the hyperspace target key should be used for this, since it can already be useful for selecting a nearby system. What about using another keybinding like `target_next` and `target_prev`?

**Comment by jjustra** [comment]
I personally used `thyperspace` practically exclusively for mission going and it seemed to make more sense to me, because you do set hyperspace, but then again I have not that much Neav hours under my belt, and some keys are still outside my muscle memory, so your judgement will probably be more insightful. I will adjust it to `target_` keys.

**Comment by jjustra** [comment]
Change made. I've added bind to `target_nearest` (do same as `target_next`) for convenience, if that is ok.

**Comment by bobbens** [comment]
Looks good, thanks for the patch! I've merged with a few changes:
1. Made the C formatting fit Naev style a bit more
2. Disable autonav functionality since it's a bit non-intuitive (you can just hit `A` to have it trigger autonav and close the window)
3. Made it center the target system when you toggle through them

**Comment by jjustra** [comment]
Thanks for fix; autonav was artifact that I forgot to remove - initial version identified currently selected system by it.

**Pull request merged**
