### PR TITLE
Fixed a typo, slightly modified some text.

### PR DESCRIPTION
**Pull request by onpon4**
Checking a dictionary, I don't think talking about a "quiet and
stable calm" is technically incorrect, but it just sounds off to me.
Maybe it's just a regional thing, but I've always thought of "calm"
as an adjective.

### CODE REVIEW

**Comment by bobbens** [comment]
Looks good, thanks.

**Comment by pydsigner** [comment]
For what it's worth, calm is definitely a legal noun. I'm not sure what dictionary you consulted, but see http://www.merriam-webster.com/dictionary/calm.

**Comment by PhoenixRiver** [comment]
Also "the calm before the storm" - definitely has use as a noun *<:@)

**Comment by l0k1** [comment]
When writing that sentence I wanted to emphasize the "calm-ness" of the bar. Like the eye of a hurricane. But I'm not terribly for it or against it.
And, yes, "quiet and stable calm" is valid English, but may be dialectical or colloquial, or possibly just older than what is commonly accepted now.
A [Google NGram Viewer search for "a quiet calm"](https://books.google.com/ngrams/graph?content=a+quiet+calm%2C+quiet+calm&case_insensitive=on&year_start=1800&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t4%3B%2Ca%20quiet%20calm%3B%2Cc0%3B%2Cs0%3B%3Ba%20quiet%20calm%3B%2Cc0%3B%3BA%20quiet%20calm%3B%2Cc0%3B.t1%3B%2Cquiet%20calm%3B%2Cc0) shows it was far more common at the turn of the 20th century, with usage dipping in the mid 20th century.

**Comment by onpon4** [comment]
pydsigner: You read the opposite of what I wrote. :o The dictionary I checked was Wiktionary, and as I said, it definitely supports the usage of "calm" here. I just think it sounds off.

**Comment by pydsigner** [comment]
Oh sure enough. Too many negatives in that sentence ;P

**Pull request merged**
