### PR TITLE
Made the "alive" bounties more doable.

### PR DESCRIPTION
**Pull request by onpon4**
Quite simply, I made the pirates in the "alive" bounty a different
faction, which the pirates consider to be an ally (and so they will
assist them), but which no one considers to be an enemy, and their
only enemy is the player. In effect, no one gets in the way by blowing
them up. Since non-lethal weapons are limited in power, and other
pirates continue to be an obstacle, this doesn't seem to cause the
mission to be overtly too easy.

### CODE REVIEW

**Comment by bobbens** [comment]
I see the reasoning behind this, but I feel it might take a bit the immersion out of it as nobody will attack the pirate except the player. Might lead to some weird situations imho.

**Comment by onpon4** [comment]
I changed this so that 70% of the time, all pilots' tasks are cleared.

**Comment by onpon4** [comment]
So, is this good? My playtesting suggests it is.

**Comment by BTAxis** [comment]
I'm inclined to think it's okay. Gameplay is by its nature player-centric anyway, so I don't think there are any immersion issues here.

**Pull request merged**
