### PR TITLE
Spacing

### PR DESCRIPTION
**Pull request by UncombedCoconut**
Helps #1280, mostly solves #1375.

### CODE REVIEW

**Comment by UncombedCoconut** [comment]
Sigh, I'm getting careless preparing the "clean" changesets. Force-pushing with forgotten file.

**Comment by onpon4** [comment]
This seems to have a whole bunch of stuff that I think is unrelated to the goal of the PR. What's happening there?

:spider:

**Comment by UncombedCoconut** [comment]
WOW! Yeah, that's not right.

**Comment by UncombedCoconut** [comment]
It is better, but it makes sense to treat this with some skepticism til I get some rest. :) In particular, I should double-check the right space-grab was committed.

**Comment by UncombedCoconut** [comment]
Famous last words, but I think it's where it should be now.
The hard part is the shipyard. It looks like this (except without the white outlines around textboxes, which are an uncommitted layout debugging aid).
The video mode here is OPENGL_WINDOW_MIN_WIDTH x OPENGL_WINDOW_MIN_HEIGHT windowed.
At larger sizes, the image grid shows more ships. (The stats are still narrow enough to require line-wrapping in German, but it looks bearable.)

shipyard-960x720-en
Schiffswerft-960x720-de
Schiffswerft-960x720-de-2

**Comment by onpon4** [comment]
I'd actually be in favor of increasing the size even more both to add some extra space for the headings (I notice that the German translation for "speed" is rather tightly packed there) and to add a buffer for the descriptions, and perhaps just a little more horizontal space for stats. (The wrapping there isn't a big deal but making it a tad less tightly packed could still be nice.) It'd mean only two columns of ships at 1024x768, but I think it'd be worth the gains in text  space.

In any case, what you've done so far looks to me like an improvement. 👍

🕵️

**Comment by onpon4** [comment]
Any updates on this one? It's still marked as a draft.

🕵️

**Comment by UncombedCoconut** [comment]
I haven't gotten to your suggestions at all. May make sense to merge this
now and iterate later.

**Pull request merged**
