### PR TITLE
Fix faders

### PR DESCRIPTION
**Pull request by Houkime**
Mouse is a bit desynced since rendering does not correspond exactly to
how mouse movements are interpreted, but otherwise fine.

faders_relatively_fixed

Codestyle needs work to blend in though.

Fixes https://github.com/naev/naev/issues/1038

### CODE REVIEW

**Comment by bobbens** [comment]
I tried to fix some of the mouse motion issues with custom widgets. However, it does seem like the movement is fairly desynced with the mouse movement. Not entirely sure where the issue can be.

**Comment by onpon4** [comment]
I think this sort of issue is why we gave up on this one.

I like that you're getting rid of those magic numbers, though I would note that consts probably shouldn't be given all-caps names (those are usually used for preprocessor macros). But I'd bet applying the same to mouse click location will eventually lead to solving the mouse click discrepancy.

**Comment by Houkime** [comment]
Changed mouse handling to mirror changes in rendering.
Seems to work flawlessly now.

faders-glorious

**Comment by bobbens** [comment]
Looks good, thanks!

**Pull request merged**
