### PR TITLE
fixed pilot.setNoDeath

### PR DESCRIPTION
**Pull request by nenau-again**
Previously, a ship with this option was set to 1hp any time it was hit.

### CODE REVIEW

**Comment by nenau-again** [comment]
Damn. There is also a problem with `setNodisable`. I'll put it on the same PR (if I manage to solve it) and I'll change the name for `setNoDisable`

**Comment by onpon4** [comment]
Just want to point where you missed some calls in the name change: one in 02_sciwrong, and several in dv_antiflf03.

🕵️

**Comment by nenau-again** [comment]
Now it should be allright. Both function do what is intended if used separately, and together as well.

**Comment by onpon4** [comment]
There's one more I think you missed, but I'll fix it. Thanks!

🕷️

**Pull request merged**
