### PR TITLE
replace setSpeedLimit in fleet_form

### PR DESCRIPTION
**Pull request by nenau**
I use a PD controller in order to avoid using setSpeedLimit in the formation hook.

### CODE REVIEW

**Comment by ids1024** [comment]
Quick testing suggests that this works better (I didn't see the circling behavior that had previously been an issue), so this looks like a good change.

**Comment by ids1024** [comment]
Note that there are other uses of `setSpeedLimit()` in fleet_form. Perhaps they could be changed as well.

**Comment by nenau** [comment]
I don't know how to avoid using setSpeedLimit for the fleader, because he is directly controlled by his AI.

**Comment by ids1024** [comment]
Ah yes, I didn't think of that.

**Comment by bobbens** [comment]
Why PD and not PID? No integral component means it will never actually reach the target orientation.

**Comment by nenau** [comment]
PID are usually used when we need to be very accurate, which is not our case imo. And having an integral corrector introduces two problems : 

* If the ship comes from far away, he will exceed it's goal
* I needed to use a memory to store the integral

Of course, there are solutions to avoid the first problem, but, this would increase the code for a minimum gain.

**Comment by bobbens** [comment]
OK, sounds good.

**Pull request merged**
