### PR TITLE
allow the player to steal ships while boarding

### PR DESCRIPTION
**Pull request by ThrosturX**
This is untested, but should work in theory, unless I made some mistakes (which is likely as I did this in about half a cup of coffee's worth of time).

### CODE REVIEW

**Comment by ThrosturX** [comment]
I've marked this as a draft, because:

- it needs the part where we compute whether or not the player can actually capture the ship (aside from `swapship` requirements)
- it needs an adequate amount of testing w.r.t. the whole `swapship`ping in space, but I have been doing a lot of it with relatively good success so far.

**Comment by bobbens** [comment]
Inspired a bit by this PR, I've written up a proposal on my thoughts of ship capturing at #2599 .

**Comment by TheGiraffe3** [comment]
So a comment in #2599, bobbens mentioned this was implemented, though still a little rough around the edges. In that case should this PR be closed?

**Comment by bobbens** [comment]
Should be closed, thanks!

**Pull request closed without merging**
